FROM fedora:36 as builder

RUN yum install koji koji-tool -y

WORKDIR /app

COPY fedora-downloader.sh fedora-downloader.sh

FROM builder as fedora-kernel

ENV kernel ""

WORKDIR /kernels

# Old method this will query last 100 koji kernel build and search for the specific kernel
# CMD koji download-build $(koji-tool builds kernel -l 100 |grep $kernel | cut -d '=' -f2) -a x86_64

CMD bash /app/fedora-downloader.sh
