name: Build Fedora kernel-crawler

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile.fedora
      - fedora-downloader.sh

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKERFILE: Dockerfile.fedora
  RELEASE_NAME: "fedora"

jobs:
  build_test_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build test image
        uses: ./.github/actions/build-test

  build_release:
    runs-on: ubuntu-latest
    needs: build_test_image

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and publish image
        uses: ./.github/actions/build-publish

    outputs:
      version: ${{ steps.release.outputs.version }}