name: Build Fedora kernel-crawler

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile.fedora
      - fedora-downloader.sh

jobs:
  build_test_image:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        id: test-image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.fedora
          tags: latest-test

  build_release:
    runs-on: ubuntu-latest
    needs: build_test_image
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile.fedora
          registry: ghcr.io
          username: "dark-vex"
          password: ${{ secrets.REPO_SCOPED_TOKEN }}
          repository: dark-vex/kernel-crawler-fedora
          tags: latest, ${{ steps.release.outputs.version }}
          push: true

    outputs:
      version: ${{ steps.release.outputs.version }}